# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42f8508055d73278b28332fde96bd69d0c8731901037ae5934c863e95bc05a3bd3e7cf3c1be4305a22c28e376d2d40e2bacbc321d5839e6ab78654c12cefba41

test:
  secret_key_base: 54ff76d683280aa3776bcdbf27aea110503090016cc9a2640ac789faf2bbc3f3a35f02719b1fabc566e22f18066475fa713fcae3b49b1a351a2ee8c5207a8f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
